### ISSUE TITLE
Latest version fails

### ISSUE THREAD

**Issue by Remi-Gau** [bids-apps/oppni#28]
```
2023-05-19T12:29:53.5919667Z ##[group]Run docker run -t --rm --read-only \
2023-05-19T12:29:53.5919998Z �[36;1mdocker run -t --rm --read-only \�[0m
2023-05-19T12:29:53.5920280Z �[36;1m  -v ${HOME}/data/ds114_test1:/bids_dataset \�[0m
2023-05-19T12:29:53.5920556Z �[36;1m  -v ${HOME}/outputs1:/outputs \�[0m
2023-05-19T12:29:53.5920785Z �[36;1m  -v /tmp:/tmp \�[0m
2023-05-19T12:29:53.5921011Z �[36;1m  -v /var/tmp:/var/tmp \�[0m
2023-05-19T12:29:53.5921252Z �[36;1m    bids/oppni:latest \�[0m
2023-05-19T12:29:53.5921508Z �[36;1m      /bids_dataset /outputs participant \�[0m
2023-05-19T12:29:53.5921798Z �[36;1m        --participant_label 01�[0m
2023-05-19T12:29:53.5978011Z shell: /usr/bin/bash -l {0}
2023-05-19T12:29:53.5978234Z ##[endgroup]
2023-05-19T12:29:56.6186411Z 	1: Not all subjects/sessions/runs have the same scanning parameters. (code: 39 - INCONSISTENT_PARAMETERS)
2023-05-19T12:29:56.6191302Z 		/sub-02/anat/sub-02_T1w.nii.gz
2023-05-19T12:29:56.6191475Z 
2023-05-19T12:29:56.6222448Z         Summary:                  Available Tasks:        Available Modalities: 
2023-05-19T12:29:56.6228004Z         16 Files, 324.57MB        finger_foot_lips        T1w                   
2023-05-19T12:29:56.6233340Z         2 - Subjects              line_bisection          dwi                   
2023-05-19T12:29:56.6238924Z         1 - Session                                       bold                  
2023-05-19T12:29:56.6242543Z 
2023-05-19T12:29:56.6276964Z 
2023-05-19T12:29:56.6286790Z run_oppni.sh /opt/mcr/v80/ /bids_dataset /outputs participant --participant 01 --run_name linebisection --task_design event
2023-05-19T12:29:56.6319258Z ---
2023-05-19T12:30:00.0983209Z Could not access the MCR component cache.
2023-05-19T12:30:00.1310166Z 
2023-05-19T12:30:00.1310831Z Unexpected error: <type 'exceptions.Exception'>
2023-05-19T12:30:00.1311167Z Traceback (most recent call last):
2023-05-19T12:30:00.1311442Z   File "/oppni/oppni.py", line 222, in <module>
2023-05-19T12:30:00.1311683Z     run_oppni()
2023-05-19T12:30:00.1311955Z   File "/oppni/oppni.py", line 199, in run_oppni
2023-05-19T12:30:00.1312336Z     run_part_one(args.bids_dir, args.participant_label, task_group, args.output_dir, args.analysis_level )
2023-05-19T12:30:00.1312698Z   File "/oppni/oppni.py", line 150, in run_part_one
2023-05-19T12:30:00.1312930Z     run_cmd(cmd)
2023-05-19T12:30:00.1313164Z   File "/oppni/oppni.py", line 67, in run_cmd
2023-05-19T12:30:00.1313467Z     raise Exception("Non zero return code: %d"%process.returncode)
2023-05-19T12:30:00.1313763Z Exception: Non zero return code: 255
```

**Comment by Remi-Gau** [comment]
see #27
